name: Titanium module

on: [push]

jobs:
  build:

    runs-on: macos-12

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Select Xcode 14.x
      run: |
        sudo xcode-select -s "/Applications/Xcode_14.0.app"
    - name: Install dependencies, build module
      run: |
        npm i -g titanium
        ti sdk install 11.1.0.GA
        cd ios
        ti build -p ios --build-only
      env:
        CI: true
